version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "fa-fifi"
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "fa-fifi"
    commit-message:
      prefix: "⬆️ "
    versioning-strategy: increase
