name: Continuous Integration

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        continue-on-error: true
        run: flutter analyze
      - name: Run tests
        if: success() || failure()
        run: flutter test